spring:
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml
    enabled: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ZmRlZWRhc3Nl
  application:
    name: pastebin
  datasource:
    url: jdbc:postgresql://localhost:5433/pastebin?user=${POSTGRES_NAME}&password=${POSTGRES_PASSWORD}
    username: ${POSTGRES_NAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true